name: MatroidGeneration
version: 2019.06.04
date: 04/06/2019
description: Generate low-rank matroids

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "images"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/images/"
    - name: "ParallelizedIterators"
      version: ">= 2018.12.09"
      url: "https://github.com/homalg-project/ParallelizedIterators"
    - name: "ArangoDBInterface"
      version: ">= 2018.12.09"
      url: "https://github.com/homalg-project/ArangoDBInterface/"
    - name: "alcove"
      version: ">= 2019-03-11"
      url: "https://github.com/martin-leuner/alcove"

www: https://github.com/homalg-project/MatroidGeneration
readme: MatroidGenerationREADME.md
packageinfo: https://github.com/homalg-project/MatroidGenerationPackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/MatroidGeneration/releases/download/v2019.06.04/MatroidGeneration-2019.06.04.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
