name: MatroidGeneration
version: "2022.06-01"
license: "GPL-2.0-or-later"
date: 2022-06-15
description: |
    Generate low-rank matroids

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "images"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/images/"
    - name: "ParallelizedIterators"
      version: ">= 2018.12.09"
      url: "https://homalg-project.github.io/pkg/ParallelizedIterators"
    - name: "ArangoDBInterface"
      version: ">= 2018.12.09"
      url: "https://homalg-project.github.io/pkg/ArangoDBInterface"
    - name: "alcove"
      version: ">= 2019-03-11"
      url: "https://github.com/martin-leuner/alcove"

www: https://homalg-project.github.io/pkg/MatroidGeneration
readme: README.md
packageinfo: https://homalg-project.github.io/MatroidGeneration/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/MatroidGeneration/releases/download/v2022.06-01/MatroidGeneration-2022.06-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/MatroidGeneration/releases/download/v2022.06-01/MatroidGeneration-2022.06-01.zip

pdf: https://github.com/homalg-project/MatroidGeneration/releases/download/v2022.06-01/MatroidGeneration-2022.06-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    matroid generation, low-rank matroids.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BK22</span>]   <b class='BibAuthor'>Barakat, M. and Kühne, L.</b>,
     <i class='BibTitle'>MatroidGeneration, Generate low-rank matroids,
             Version 2022.06-01</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/MatroidGeneration">https://homalg-project.github.io/pkg/MatroidGeneration</a></span>.
    </p>
    

bibtex: |
    @misc{ MatroidGeneration2022.06-01,
      author =           {Barakat, M. and K{\"u}hne, L.},
      title =            {{MatroidGeneration},   Generate   low-rank   matroids,
                          {V}ersion 2022.06-01},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/MatroidGeneration}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{MatroidGeneration}}},
      keywords =         {matroid generation, low-rank matroids},
      printedkey =       {BK22}
    }

